os: linux
dist: trusty
language: python
services: docker

env:
  global:
  - SMARTGIT_VER=17.1.2

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - 'docker build --build-arg SMARTGIT_VER=$SMARTGIT_VER
                  --tag x11vnc/smartgit-desktop:latest
                  --tag x11vnc/smartgit-desktop:$SMARTGIT_VER . &&
     docker push x11vnc/smartgit-desktop &&
     touch success'
  - docker images
